# frozen_string_literal: true

# Swiftlint
swiftlint.binary_path = 'iosApp/Pods/SwiftLint/swiftlint'
swiftlint.config_file = 'iosApp/.swiftlint.yml'
swiftlint.max_num_violations = 20
swiftlint.lint_files(
  inline_mode: true,
  fail_on_error: false,
  additional_swiftlint_args: '--strict'
)

# Xcov
# Generate report
report = xcov.produce_report(
  scheme: "Survey",
  workspace: "iosApp/Survey.xcworkspace",
  only_project_targets: true,
  markdown_report: true,
  html_report: false
)

# Post markdown report
xcov.output_report(report)
