# frozen_string_literal: true

require './iosApp/fastlane/Constants/Constants'

# SwiftFormat
swiftformat.binary_path = 'iosApp/Pods/SwiftFormat/CommandLineTool/swiftformat'
swiftformat.exclude = %w(Pods/**  **/*generated.swift)
swiftformat.check_format

# Swiftlint
swiftlint.binary_path = 'iosApp/Pods/SwiftLint/swiftlint'
swiftlint.max_num_violations = 20
swiftlint.lint_all_files = true
swiftlint.lint_files(
  inline_mode: true,
  fail_on_error: true,
  additional_swiftlint_args: '--strict'
)

xcresultPath = "iosApp/#{Constants.TEST_OUTPUT_DIRECTORY_PATH}/#{Constants.TESTS_SCHEME}.xcresult"

# Xcode summary
changed_files = (git.modified_files - git.deleted_files) + git.added_files
xcode_summary.ignored_results { |result|
  if result.location
    not changed_files.include?(result.location.file_path) &&
    not result.location.file_path.include?("AA_AppLoadSpec.swift")
  else
    true
  end
}
xcode_summary.ignored_files = 'iosApp/Pods/**'
xcode_summary.inline_mode = true
xcode_summary.report xcresultPath

# Xcov
xcov.report(
  scheme: Constants.TESTS_SCHEME,
  workspace: "iosApp/#{Constants.WORKSPACE_PATH}",
  output_directory: "iosApp/#{Constants.XCOV_OUTPUT_DIRECTORY_PATH}",
  xccov_file_direct_path: xcresultPath,
  only_project_targets: true,
  markdown_report: true,
  html_report: false
)
